// <auto-generated />
namespace Cantina_MasterSD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cantina03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cantina03));
        
        string IMigrationMetadata.Id
        {
            get { return "202207211913173_cantina03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
